### ISSUE TITLE
Fix Several Security Issues and Update Dependencies

### ISSUE THREAD

**Issue by pandres95** [BoolJS/booljs.github.io#2]
## What kind of Issue is this?

- Bug.

## Can you please explain this Issue?

In order to guarantee we can keep providing a stable and safe toolkit for our users,  we need to fix the currently solved security issues already reported in _npm_.

## What's the expected behaviour?

Dependencies must be up to date and addressable security issues must be solved.

## What are the steps to complete this issue?

- [ ] Update the dependencies (by running `npm update`)
- [ ] Fix security issues (by running `npm audit --fix`)

## What's the current behaviour?

There are security issues reported with the following packages:

- [mixin-deep](https://npm.im/mixin-deep)
- [lodash](https://npm.im/lodash)
- [lodash.merge](https://npm.im/lodash.merge)
- [underscore.string](https://npm.im/underscore.string)
- [remarkable](https://npm.im/remarkable)

**Comment by aradkdj** [comment]
can i take this?

**Comment by pandres95** [comment]
Yup @aradkdj, you can!
